name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use the version of Python compatible with Streamlit

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your app's dependencies

      # Step 4: Run the Streamlit app
      - name: Run Streamlit
        env:
          DB_USER: ${{ secrets.DB_USER }}  # Pass the DB_USER secret
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Pass the DB_PASSWORD secret
        run: |
          streamlit run streamlit_app.py --server.port 8501
